### ISSUE TITLE
A really awesome feature

### ISSUE THREAD

**Issue by cynthiateeters** [RVCC-IDMX/foobar-template#1]
A description

## Todo

- [ ] Set up a backend
- [ ] Write an API
- [ ] Do some frontend
